"""empty message

Revision ID: ba0cb1f6b183
Revises: 13b562b8f08d
Create Date: 2018-02-25 15:32:47.941480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba0cb1f6b183'
down_revision = '13b562b8f08d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work', sa.Column('youtube_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work', 'youtube_url')
    # ### end Alembic commands ###
